global-message-format: '{_GRAY}<{sender}>{_WHITE} {message}'
direct-message-sender-format: '{_GRAY}<YOU -> {target}>{_WHITE} {message}'
direct-message-target-format: '{_GRAY}<{sender} -> YOU>{_WHITE} {message}'
