name: build
on:
  push:
    branches:
      - main
jobs:
  build-1-19-1:
    name: Build for Minecraft 1.19.1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout.
        id: checkout
        uses: actions/checkout@v3
      - name: Setup Java.
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build the plugin.
        id: build
        uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.19.1
      - name: Create GitHub release.
        id: release
        uses: CupOfTea696/gh-action-auto-release@v1
        with:
          title: $version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to GitHub release.
        id: upload
        uses: Fhwang0926/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: '*.jar'
          asset_label: 1.19.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
