name: build
on:
  push:
    branches:
      - main
jobs:
  build-1-19-1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: SpraxDev/Action-SpigotMC@v4
        with:
          version: 1.19.1
