name: build
on:
  push:
    branches:
      - main
jobs:
  build-1-19-1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.19.1
